version: '3'

services:
  mysql:
    image: mysql:5.7
    platform: linux/amd64
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: orders
      MYSQL_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - .docker/mysql:/var/lib/mysql
  
  migrate:
    image: mysql:5.7
    platform: linux/amd64
    container_name: migrate
    restart: "no"
    depends_on:
      - mysql
    entrypoint: >
      bash -c "
        sleep 15 &&
        mysql -h mysql -u root -proot orders < /docker-entrypoint-initdb.d/init.sql
      "
    volumes:
      - ./migrations/init.sql:/docker-entrypoint-initdb.d/init.sql

  rabbitmq:
    image: rabbitmq:3-management
    platform: linux/amd64
    container_name: rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest